// Code generated by MockGen. DO NOT EDIT.
// Source: realization/board.go
//
// Generated by this command:
//
//	mockgen -source=realization/board.go -destination=mocks/mock_board.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	"seabattle/review_seabattle/realization"
)

type orientation int

const (
	gorizontal orientation = iota
	vertical
)

// MockBoard is a mocks of Board interface.
type MockBoard struct {
	ctrl     *gomock.Controller
	recorder *MockBoardMockRecorder
	isgomock struct{}
}

// MockBoardMockRecorder is the mocks recorder for MockBoard.
type MockBoardMockRecorder struct {
	mock *MockBoard
}

// NewMockBoard creates a new mocks instance.
func NewMockBoard(ctrl *gomock.Controller) *MockBoard {
	mock := &MockBoard{ctrl: ctrl}
	mock.recorder = &MockBoardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoard) EXPECT() *MockBoardMockRecorder {
	return m.recorder
}

// HandleShoot mocks base method.
func (m *MockBoard) HandleShoot(arg0, arg1 int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleShoot", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// HandleShoot indicates an expected call of HandleShoot.
func (mr *MockBoardMockRecorder) HandleShoot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleShoot", reflect.TypeOf((*MockBoard)(nil).HandleShoot), arg0, arg1)
}

// PlaceShipCoords mocks base method.
func (m *MockBoard) PlaceShipCoords(arg0, arg1, arg2 int, arg3 orientation) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceShipCoords", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PlaceShipCoords indicates an expected call of PlaceShipCoords.
func (mr *MockBoardMockRecorder) PlaceShipCoords(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceShipCoords", reflect.TypeOf((*MockBoard)(nil).PlaceShipCoords), arg0, arg1, arg2, arg3)
}

// PlaceShipRandom mocks base method.
func (m *MockBoard) PlaceShipRandom(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceShipRandom", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PlaceShipRandom indicates an expected call of PlaceShipRandom.
func (mr *MockBoardMockRecorder) PlaceShipRandom(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceShipRandom", reflect.TypeOf((*MockBoard)(nil).PlaceShipRandom), arg0)
}

// PrintField mocks base method.
func (m *MockBoard) PrintField() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintField")
}

// PrintField indicates an expected call of PrintField.
func (mr *MockBoardMockRecorder) PrintField() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintField", reflect.TypeOf((*MockBoard)(nil).PrintField))
}

// MockCell is a mocks of Cell interface.
type MockCell struct {
	ctrl     *gomock.Controller
	recorder *MockCellMockRecorder
	isgomock struct{}
}

// MockCellMockRecorder is the mocks recorder for MockCell.
type MockCellMockRecorder struct {
	mock *MockCell
}

// NewMockCell creates a new mocks instance.
func NewMockCell(ctrl *gomock.Controller) *MockCell {
	mock := &MockCell{ctrl: ctrl}
	mock.recorder = &MockCellMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCell) EXPECT() *MockCellMockRecorder {
	return m.recorder
}

// GetShip mocks base method.
func (m *MockCell) GetShip() realization.Ship {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShip")
	ret0, _ := ret[0].(realization.Ship)
	return ret0
}

// GetShip indicates an expected call of GetShip.
func (mr *MockCellMockRecorder) GetShip() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShip", reflect.TypeOf((*MockCell)(nil).GetShip))
}

// GetStatus mocks base method.
func (m *MockCell) GetStatus() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockCellMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockCell)(nil).GetStatus))
}

// SetShip mocks base method.
func (m *MockCell) SetShip(ship realization.Ship) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetShip", ship)
}

// SetShip indicates an expected call of SetShip.
func (mr *MockCellMockRecorder) SetShip(ship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShip", reflect.TypeOf((*MockCell)(nil).SetShip), ship)
}

// SetStatus mocks base method.
func (m *MockCell) SetStatus(status bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockCellMockRecorder) SetStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockCell)(nil).SetStatus), status)
}
