// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/board.go
//
// Generated by this command:
//
//	mockgen -source=interfaces/board.go -destination=mocks/board_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBoard is a mock of Board interface.
type MockBoard struct {
	ctrl     *gomock.Controller
	recorder *MockBoardMockRecorder
	isgomock struct{}
}

// MockBoardMockRecorder is the mock recorder for MockBoard.
type MockBoardMockRecorder struct {
	mock *MockBoard
}

// NewMockBoard creates a new mock instance.
func NewMockBoard(ctrl *gomock.Controller) *MockBoard {
	mock := &MockBoard{ctrl: ctrl}
	mock.recorder = &MockBoardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoard) EXPECT() *MockBoardMockRecorder {
	return m.recorder
}

// HandleShoot mocks base method.
func (m *MockBoard) HandleShoot(arg0, arg1 int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleShoot", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// HandleShoot indicates an expected call of HandleShoot.
func (mr *MockBoardMockRecorder) HandleShoot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleShoot", reflect.TypeOf((*MockBoard)(nil).HandleShoot), arg0, arg1)
}

// PlaceShipCoords mocks base method.
func (m *MockBoard) PlaceShipCoords(arg0, arg1, arg2 int, arg3 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceShipCoords", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PlaceShipCoords indicates an expected call of PlaceShipCoords.
func (mr *MockBoardMockRecorder) PlaceShipCoords(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceShipCoords", reflect.TypeOf((*MockBoard)(nil).PlaceShipCoords), arg0, arg1, arg2, arg3)
}

// PlaceShipRandom mocks base method.
func (m *MockBoard) PlaceShipRandom(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceShipRandom", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PlaceShipRandom indicates an expected call of PlaceShipRandom.
func (mr *MockBoardMockRecorder) PlaceShipRandom(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceShipRandom", reflect.TypeOf((*MockBoard)(nil).PlaceShipRandom), arg0)
}

// PrintField mocks base method.
func (m *MockBoard) PrintField() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintField")
}

// PrintField indicates an expected call of PrintField.
func (mr *MockBoardMockRecorder) PrintField() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintField", reflect.TypeOf((*MockBoard)(nil).PrintField))
}
