// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/cell.go
//
// Generated by this command:
//
//	mockgen -source=interfaces/cell.go -destination=mocks/cell_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	interfaces "seabattle/seabattle/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockCell is a mock of Cell interface.
type MockCell struct {
	ctrl     *gomock.Controller
	recorder *MockCellMockRecorder
	isgomock struct{}
}

// MockCellMockRecorder is the mock recorder for MockCell.
type MockCellMockRecorder struct {
	mock *MockCell
}

// NewMockCell creates a new mock instance.
func NewMockCell(ctrl *gomock.Controller) *MockCell {
	mock := &MockCell{ctrl: ctrl}
	mock.recorder = &MockCellMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCell) EXPECT() *MockCellMockRecorder {
	return m.recorder
}

// GetShip mocks base method.
func (m *MockCell) GetShip() interfaces.Ship {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShip")
	ret0, _ := ret[0].(interfaces.Ship)
	return ret0
}

// GetShip indicates an expected call of GetShip.
func (mr *MockCellMockRecorder) GetShip() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShip", reflect.TypeOf((*MockCell)(nil).GetShip))
}

// GetStatus mocks base method.
func (m *MockCell) GetStatus() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockCellMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockCell)(nil).GetStatus))
}

// SetShip mocks base method.
func (m *MockCell) SetShip(ship interfaces.Ship) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetShip", ship)
}

// SetShip indicates an expected call of SetShip.
func (mr *MockCellMockRecorder) SetShip(ship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShip", reflect.TypeOf((*MockCell)(nil).SetShip), ship)
}

// SetStatus mocks base method.
func (m *MockCell) SetStatus(status bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockCellMockRecorder) SetStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockCell)(nil).SetStatus), status)
}
