// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/ship.go
//
// Generated by this command:
//
//	mockgen -source=interfaces/ship.go -destination=mocks/ship_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	"seabattle/seabattle/interfaces"
)

// MockShip is a mock of Ship interface.
type MockShip struct {
	ctrl     *gomock.Controller
	recorder *MockShipMockRecorder
	isgomock struct{}
}

// MockShipMockRecorder is the mock recorder for MockShip.
type MockShipMockRecorder struct {
	mock *MockShip
}

// NewMockShip creates a new mock instance.
func NewMockShip(ctrl *gomock.Controller) *MockShip {
	mock := &MockShip{ctrl: ctrl}
	mock.recorder = &MockShipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShip) EXPECT() *MockShipMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockShip) GetStatus() interfaces.ShipStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(interfaces.ShipStatus)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockShipMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockShip)(nil).GetStatus))
}

// HandleShoot mocks base method.
func (m *MockShip) HandleShoot(x, y int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleShoot", x, y)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HandleShoot indicates an expected call of HandleShoot.
func (mr *MockShipMockRecorder) HandleShoot(x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleShoot", reflect.TypeOf((*MockShip)(nil).HandleShoot), x, y)
}
